### ISSUE TITLE
无法显示弹幕

### ISSUE THREAD

**Issue by MistEO** [kokolokksk/muamuamua#10]
版本 [v1.2.7](https://github.com/kokolokksk/catcat-dm/tree/v1.2.7) 

试了一下老版本 [dom-v-1.1.1](https://github.com/kokolokksk/catcat-dm/tree/dom-v-1.1.1) 是正常的，仅新版本有这个问题

![image](https://user-images.githubusercontent.com/18511905/159108850-afc2f9d8-cbc2-449a-ba8b-ed2f329ac50c.png)

**Comment by LoveLoliii** [comment]
已修复。
