### ISSUE TITLE
1.4.1 bug似乎有点多（

### ISSUE THREAD

**Issue by MistEO** [kokolokksk/muamuamua#11]
1. 弹幕发不出去，设置里都是正常填写的，重启进程仍无效
2. 弹幕延时很大，经常收不到弹幕，过个几秒一下子蹦出来好多
3. 当弹幕数量超过一个窗口能显示的数量了，最后一条会被挡住

**Comment by LoveLoliii** [comment]
👌

**Comment by MistEO** [comment]
问题 2 似乎不存在，是因为问题 3 导致的，不止一条被挡住了，而是 N 条都被挡住了。然后不知道什么时候就会突然全蹦出来（

v1.3.8 也存在这个问题，不过 v1.3.8 弹幕可以正常发

**Comment by LoveLoliii** [comment]
> 

好的 明天摸鱼修下
