### ISSUE TITLE
开启弹幕姬后希望可以关闭设置界面

### ISSUE THREAD

**Issue by MistEO** [kokolokksk/muamuamua#12]
![image](https://user-images.githubusercontent.com/18511905/168416174-ef2e290c-2c4e-46bf-88db-74c20710422d.png)

就是这个界面，以前是可以关掉的（弹幕姬不会退出），现在关掉就退出进程了

**Comment by LoveLoliii** [comment]
现在可以安全的关闭啦，不过要手动关。
