### ISSUE TITLE
v1.4.3 最后一条弹幕仍会被挡住

### ISSUE THREAD

**Issue by MistEO** [kokolokksk/muamuamua#13]
开到最大化可以看到最下面还有一条弹幕，但是不开全屏这条就看不见了

并且倒数第二条 “早呀” 也被挡住了一小半

![image](https://user-images.githubusercontent.com/18511905/168420897-607b27a1-0cad-4dd8-8e48-3c4367e05590.png)

![image](https://user-images.githubusercontent.com/18511905/168420916-14679cd9-1e5b-4017-8bd0-6b4d25e27fd3.png)

**Comment by MistEO** [comment]
似乎即使最大化也没法保证一定能显示全部弹幕，可以看到最后一条是被挡住了一半的。

去网页端看，后面还有两条（

![image](https://user-images.githubusercontent.com/18511905/168421544-eb183830-8abf-4a8c-aad4-0213e2a81049.png)

![image](https://user-images.githubusercontent.com/18511905/168421559-b33ed158-ee4d-4be9-93d8-a27ffb88ea85.png)

**Comment by LoveLoliii** [comment]
这个高度计算 我得在看下

**Comment by LoveLoliii** [comment]
solved
