### ISSUE TITLE
咕咕了么？

### ISSUE THREAD

**Issue by MistEO** [kokolokksk/muamuamua#7]
rt

**Comment by LoveLoliii** [comment]
挺完善的呀

**Comment by MistEO** [comment]
那我可要提需求了！

**Comment by LoveLoliii** [comment]
![Uploading QQ图片20210430142311.png…]()

**Comment by LoveLoliii** [comment]
你说 我记着呢

**Comment by MistEO** [comment]
置顶功能经常不可用，设置里确认已经开了。需要重新开关一遍并重启进程才能生效

**Comment by MistEO** [comment]
收到礼物消息最好别直接覆盖，经常看不到礼物2333和弹幕一起滚动？

**Comment by LoveLoliii** [comment]
> 置顶功能经常不可用，设置里确认已经开了。需要重新开关一遍并重启进程才能生效



> 收到礼物消息最好别直接覆盖，经常看不到礼物2333和弹幕一起滚动？
好的 记下来

**Comment by LoveLoliii** [comment]
> 收到礼物消息最好别直接覆盖，经常看不到礼物2333和弹幕一起滚动？

后面用一个新的礼物窗口来显示
