### ISSUE TITLE
打不开

### ISSUE THREAD

**Issue by MistEO** [kokolokksk/muamuamua#8]
![image](https://user-images.githubusercontent.com/18511905/140619232-53d63a8d-f99e-447d-80fe-a594c0a2f118.png)
RT，窗口si似乎被隐藏了一样。使用的是最新的release

**Comment by MistEO** [comment]
退出重开、结束进程重开，均无效

**Comment by LoveLoliii** [comment]
试下删除 %APPDATA%/mua  文件夹
