### ISSUE TITLE
偶现启动后不连接直播间

### ISSUE THREAD

**Issue by MistEO** [kokolokksk/muamuamua#9]
像这样

![image](https://user-images.githubusercontent.com/18511905/159108735-700d4d4a-1533-4f23-8c67-460594fc1498.png)

重启软件，什么都不修改，就又正常了

![image](https://user-images.githubusercontent.com/18511905/159108752-3fcb0654-35db-4037-bf4a-bb3e48f849ba.png)

**Comment by MistEO** [comment]
版本：[dom-v-1.1.1](https://github.com/kokolokksk/catcat-dm/tree/dom-v-1.1.1) 和 [v1.2.7](https://github.com/kokolokksk/catcat-dm/tree/v1.2.7) 都有这个问题

**Comment by LoveLoliii** [comment]
已修复。
